apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud-deployment
resources:
  - ../../base/nextcloud-deployment
# removed secret.yaml as it is generated secretGenerator

images:
  - name: nextcloud
    newName: nextcloud
    newTag: 30.0.0

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nextcloud.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: nextcloud.example.com
    target:
      kind: Ingress
      name: nextcloud-ingress

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: credentials-secret
    behavior: merge
    files:
      - secret.yaml

configMapGenerator:
  - name: nextcloud-config-sh
    files:
      - config.sh

  - name: nextcloud-configuration
    literals:
      - nextcloud_trusted_domains=nextcloud.example.com
      - cli_url=https://nextcloud.example.com
      - nextcloud_admin_user=admin
      - redis_host=redis
      - php_memory_limit=716M
      - php_upload_limit=10G

  - name: mariadb-configuration
    literals:
      - mariadb_db=nextcloud
      - mariadb_user=nextcloud
      - mariadb_host=mariadb-service
      - mariadb_init=--locale=C --encoding=UTF-8
