apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mariadb
  type: ClusterIP
  selector:
    app: mariadb

